2017-02-07 10:13:51  [ main:0 ] - [ DEBUG ]  This is debug message.
2017-02-07 10:13:51  [ main:16 ] - [ INFO ]  This is info message.
2017-02-07 10:13:51  [ main:16 ] - [ ERROR ]  This is error message.
2017-02-07 10:19:57  [ main:0 ] - [ INFO ]  a is : 10
2017-02-07 10:24:05  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 10:24:05  [ main:14 ] - [ INFO ]  testMethodTwo-- Test method failed
2017-02-07 10:24:05  [ main:20 ] - [ INFO ]  testMethodThree-- test method skipp
2017-02-07 14:06:38  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:06:38  [ main:9 ] - [ INFO ]  testMethodTwo-- Test method failed
2017-02-07 14:06:38  [ main:18 ] - [ INFO ]  testMethodThree-- test method skipp
2017-02-07 14:38:40  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:38:40  [ main:11 ] - [ ERROR ]  FAIL org.testng.internal.TestResult testMethodTwo
2017-02-07 14:38:40  [ main:11 ] - [ ERROR ]  java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.testng.demo.SampleTest.testMethodTwo(SampleTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

2017-02-07 14:38:40  [ main:14 ] - [ INFO ]  testMethodThree-- test method skipp
2017-02-07 14:40:10  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:40:10  [ main:11 ] - [ ERROR ]  FAIL org.testng.internal.TestResult testMethodTwo
2017-02-07 14:40:10  [ main:14 ] - [ INFO ]  testMethodThree-- test method skipp
2017-02-07 14:40:53  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:40:53  [ main:13 ] - [ ERROR ]  FAIL org.testng.internal.TestResult testMethodTwo
2017-02-07 14:40:53  [ main:14 ] - [ ERROR ]  java.lang.AssertionError: expected [true] but found [false]
2017-02-07 14:40:53  [ main:17 ] - [ INFO ]  testMethodThree-- test method skipp
2017-02-07 14:42:12  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:42:29  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:43:10  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:45:51  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:45:51  [ main:11 ] - [ ERROR ]  FAIL org.testng.internal.TestResult testMethodTwo expected [true] but found [false]
2017-02-07 14:45:51  [ main:15 ] - [ INFO ]  testMethodThree-- test method skipp
2017-02-07 14:47:20  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:47:20  [ main:8 ] - [ ERROR ]  FAIL org.testng.internal.TestResult testMethodTwo reason:expected [true] but found [false]
2017-02-07 14:47:20  [ main:9 ] - [ ERROR ]  
2017-02-07 14:47:20  [ main:11 ] - [ INFO ]  testMethodThree-- test method skipp
2017-02-07 14:47:56  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:47:56  [ main:10 ] - [ ERROR ]  FAIL org.testng.internal.TestResult testMethodTwo reason:expected [true] but found [false]
2017-02-07 14:47:56  [ main:10 ] - [ ERROR ]  java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.testng.demo.SampleTest.testMethodTwo(SampleTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

2017-02-07 14:47:56  [ main:13 ] - [ INFO ]  testMethodThree-- test method skipp
2017-02-07 14:50:33  [ main:0 ] - [ INFO ]  testMethodOne-- Test method succ
2017-02-07 14:50:33  [ main:13 ] - [ ERROR ]  FAIL org.testng.internal.TestResult testMethodTwo reason:expected [true] but found [false]
2017-02-07 14:50:33  [ main:13 ] - [ ERROR ]  java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.testng.demo.SampleTest.testMethodTwo(SampleTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

2017-02-07 14:50:33  [ main:17 ] - [ INFO ]  testMethodThree-- test method skipp
